### ISSUE TITLE
Getting an error retrieving wordlestats

### ISSUE THREAD

**Issue by doctormari** [jakehlee/JDG-Cogs-V3#12]
[p]wordlestats works for everyone else but me, the error message states it's diving by zero:

```
[2023-03-20 15:55:32] [ERROR] red: Exception in command 'wordlestats'
Traceback (most recent call last):
  File "/data/venv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/data/cogs/CogManager/cogs/wordle/wordle.py", line 124, in wordlestats
    percs = [int((x/totalgames)*100) for x in memberstats['qty']]
  File "/data/cogs/CogManager/cogs/wordle/wordle.py", line 124, in <listcomp>
    percs = [int((x/totalgames)*100) for x in memberstats['qty']]
ZeroDivisionError: division by zero
```

I tried uninstalling and reinstalling, reparsing, etc. Have not been able to resolve on my own.

**Comment by jakehlee** [comment]
Hey, thanks for the issue. I think it might be complaining because it doesn't have any games on record for you. Still, it should actually post an error message, not just throw an Error. Could you confirm if that's the case though?

**Comment by doctormari** [comment]
Welcome! I've posted almost everyday for about six months, so I have some recorded games it should parse in if that's what you mean. When I post the results for today, for example, it won't recognize me and give the "great solve" message. I will add an example from today if that is of any help:
![Snag_113cf558](https://user-images.githubusercontent.com/12752913/226504864-0063644e-029f-439a-ad3c-40464e88edea.png)

**Comment by jakehlee** [comment]
The error is because the bot seems to have lost your history of games - that's okay though, I have a command included to re-parse the entire channel's history again, which should work (might take a while though). The bigger question is why it's not recognizing your games, I'm wondering if NYT/wordle might've changed something on me, especially since your yellow squares look different from the other user's.

Could you copy-paste your wordle squares and another user's squares directly into this issue?

**Comment by jakehlee** [comment]
I could also just start playing wordle again, I'll give that a shot

**Comment by jakehlee** [comment]
Here it is for a normal game, 

```
Wordle 639 4/6

⬛🟨⬛⬛⬛
⬛⬛🟩⬛🟨
🟩🟩🟩⬛⬛
🟩🟩🟩🟩🟩
```

Here it is for a hard game:

```
Wordle 639 4/6*

⬛🟨⬛⬛⬛
⬛⬛🟩⬛⬛
⬛🟩🟩🟩🟩
🟩🟩🟩🟩🟩
```

I only see 🟨  which is ` LARGE YELLOW SQUARE `

But I think you're using 🟧 which is ` LARGE ORANGE SQUARE `

**Comment by doctormari** [comment]
Ah yes I see, I tried it again this morning and turned off High Contrast mode. It worked. Good catch! I had not considered that.

![Snag_1328d1ca](https://user-images.githubusercontent.com/12752913/226592128-6030cdd6-d3a1-4d0a-a46e-ebd0ed54404e.png)

Here are the squares used in High Contrast mode: blue and orange.
![image](https://user-images.githubusercontent.com/12752913/226677980-c0012028-0379-46b5-881b-e9f12ddf8e25.png)

**Comment by jakehlee** [comment]
Aha, I didn't know that existed. I also got thrown off because I assumed blue = placed and orange = unplaced but it's actually the opposite.

```
Wordle 640 X/6

⬛🟧🟦⬛⬛
⬛⬛🟦⬛🟦
🟦🟦🟦⬛⬛
⬛🟧🟧⬛🟦
⬛🟧🟧🟦🟧
🟧🟧🟧⬛🟧
```

**Comment by doctormari** [comment]
Awesome, thanks again. Works beautifully. Excellent cog.
