### ISSUE TITLE
[Suggestion]Reparse

### ISSUE THREAD

**Issue by Ginpachi98** [jakehlee/JDG-Cogs-V3#8]
Hmm, is there a way to make it reparse threads within a channel?

**Comment by jakehlee** [comment]
I hadn't even considered that as a possibility (I can't say I've ever used Discord's thread feature, my servers are relatively small), thanks for the suggestion! I'll take a look to see how that's handled in discord.py.

**Comment by Ginpachi98** [comment]
I checked, Red is based on 1.7.3 discord.py, which doesn't support threads. :(
